// Synonym map for search engine. Russian queries → recipe tags.
// Keys are lowercased query substrings (without word boundaries needed).
// Values are tags to match against recipe.cuisine / .protein / .textures / .sauceChar / .moods / .keyIngredients.

export const SYNONYMS = {
  // textures
  'хрустящ': ['crunch', 'crispy-fried'],
  'хруст': ['crunch', 'crispy-fried'],
  'crisp': ['crunch', 'crispy-fried'],
  'свеж': ['fresh', 'crunch'],
  'сыр': ['cheese', 'paneer', 'halloumi', 'parmesan', 'burrata', 'feta'],
  'шёлков': ['silky', 'creamy'],
  'шелков': ['silky', 'creamy'],
  'сливочн': ['silky', 'creamy'],
  'крем': ['silky', 'creamy'],
  'нежн': ['silky', 'creamy'],
  'сочн': ['juicy'],
  'мягк': ['silky'],
  'плотн': ['hearty'],

  // sauce character
  'остр': ['spicy-hot'],
  'жгуч': ['spicy-hot'],
  'огнен': ['spicy-hot'],
  'spicy': ['spicy-hot'],
  'перчён': ['spicy-hot'],
  'сладко-солён': ['sweet-savory'],
  'карамел': ['sweet-savory', 'caramelized'],
  'медов': ['sweet-savory'],
  'кисл': ['sour-bright', 'citrus'],
  'лимон': ['citrus', 'lemon'],
  'цитрус': ['citrus'],
  'граната': ['pomegranate', 'sour-bright'],
  'гранат': ['pomegranate', 'sour-bright'],
  'кислинк': ['sour-bright'],
  'умам': ['umami'],
  'соев': ['soy', 'umami'],
  'устричн': ['umami'],
  'хойсин': ['umami', 'sweet-savory'],
  'гочуджан': ['spicy-hot', 'umami'],
  'кочучан': ['spicy-hot', 'umami'],
  'мисо': ['umami', 'silky'],
  'трав': ['herbal'],
  'базилик': ['basil', 'herbal'],
  'кинз': ['cilantro', 'herbal'],
  'кориандр': ['cilantro', 'herbal'],
  'мята': ['herbal'],
  'эстрагон': ['herbal'],
  'шалф': ['sage', 'herbal'],
  'розмарин': ['herbal'],
  'тимьян': ['herbal'],

  // cooking method
  'жарен': ['pan-fry', 'sear', 'stir-fry'],
  'фри': ['crispy-fried', 'deep-fry'],
  'тушён': ['braise'],
  'тушен': ['braise'],
  'гриль': ['grill'],
  'на огне': ['grill'],
  'шашлык': ['grill', 'skewer'],
  'кебаб': ['grill', 'skewer'],
  'шпажк': ['grill', 'skewer'],
  'тако': ['mexican', 'flatbread'],
  'лаваш': ['flatbread'],
  'тортилья': ['flatbread'],
  'wok': ['wok', 'stir-fry'],
  'вок': ['wok', 'stir-fry'],
  'рагу': ['braise', 'hearty'],
  'тёпл': ['warm', 'hearty'],

  // cuisines
  'итал': ['italy'],
  'пицц': ['italy', 'pizza'],
  'паст': ['italy', 'pasta'],
  'спагет': ['italy', 'pasta'],
  'кита': ['china'],
  'азиат': ['china', 'japan', 'korea', 'thailand', 'vietnam', 'indonesia'],
  'япон': ['japan'],
  'кор': ['korea'],
  'тай': ['thailand'],
  'вьетнам': ['vietnam'],
  'индонез': ['indonesia'],
  'инд': ['india'],
  'мексик': ['mexico', 'latin'],
  'латин': ['latin'],
  'перу': ['peru', 'latin'],
  'аргент': ['latin'],
  'бразил': ['latin'],
  'турец': ['turkey'],
  'француз': ['france'],
  'марок': ['morocco', 'middle-east'],
  'ливан': ['middle-east'],
  'израил': ['middle-east'],
  'греч': ['middle-east', 'greek'],
  'средиземн': ['middle-east'],

  // protein
  'говяд': ['beef'],
  'стейк': ['beef', 'steak'],
  'фарш': ['beef', 'turkey', 'pork'],
  'свин': ['pork'],
  'кур': ['chicken'],
  'крыл': ['chicken'],
  'бедр': ['chicken'],
  'грудк': ['chicken'],
  'индейк': ['turkey'],
  'панир': ['paneer', 'vegetarian'],
  'халлум': ['halloumi', 'vegetarian'],
  'фета': ['feta', 'vegetarian'],
  'без мяса': ['vegetarian'],
  'вегет': ['vegetarian'],
  'постн': ['vegetarian'],
  'овощ': ['vegetarian', 'fresh'],

  // ingredients / dishes
  'томат': ['tomato'],
  'помидор': ['tomato'],
  'риcс': ['rice'],
  'рис': ['rice'],
  'лапш': ['noodles'],
  'нудл': ['noodles'],
  'удон': ['noodles', 'japan'],
  'рамен': ['noodles', 'japan'],
  'картош': ['potato'],
  'картофел': ['potato'],
  'имбир': ['ginger'],
  'чесн': ['garlic'],
  'мёд': ['honey', 'sweet-savory'],
  'мед': ['honey', 'sweet-savory'],
  'болонез': ['bolognese', 'italy', 'pasta'],
  'болонья': ['bolognese', 'italy', 'pasta'],
  'карри': ['curry'],
  'тикка': ['curry', 'india'],
  'масала': ['curry', 'india'],
  'тако': ['mexican'],
  'буррит': ['mexican'],
  'фахит': ['mexican'],
  'булгог': ['korea'],
  'кальб': ['korea'],
  'катсу': ['japan'],
  'терияк': ['japan'],
  'ризотто': ['italy'],
  'гнокки': ['italy'],
  'лазань': ['italy'],
  'тажин': ['morocco', 'braise'],
  'таджин': ['morocco', 'braise'],
  'тахин': ['middle-east'],
  'тахини': ['middle-east'],
  'заатар': ['middle-east'],
  'харисс': ['spicy-hot', 'middle-east'],
  'чимич': ['herbal', 'latin'],
  'буррат': ['burrata', 'italy'],
  'парм': ['parmesan', 'italy'],
  'песто': ['herbal', 'italy'],
  'трюфел': ['truffle', 'umami'],

  // moods (still useful)
  'быстр': ['quick'],
  'мин': ['quick'],
  'устал': ['quick', 'comforting'],
  'уютн': ['comforting', 'hearty'],
  'праздн': ['fancy', 'fancy-night'],
};

// Sensory chips → tag bundles. Used by feel-by-touch entries.
export const FEELINGS = {
  'crunch': {
    label: 'Хрустящее свежее',
    emoji: '🥬',
    tagline: 'Горячее блюдо с прохладным crunchy элементом',
    match: { any: ['crunch', 'fresh'] },
  },
  'silky': {
    label: 'Шёлковое сливочное',
    emoji: '🧈',
    tagline: 'Кремовые соусы, бархатный вкус',
    match: { any: ['silky', 'creamy'] },
  },
  'fire': {
    label: 'Огненное',
    emoji: '🔥',
    tagline: 'Жгучее, с чили, харисса, сычуань',
    match: { any: ['spicy-hot'], minSpice: 2 },
  },
  'juicy': {
    label: 'Сочное',
    emoji: '💧',
    tagline: 'Мясо, истекающее соком',
    match: { any: ['juicy'] },
  },
  'sour': {
    label: 'Кислое-яркое',
    emoji: '🍋',
    tagline: 'Цитрус, гранат, уксус — будит вкус',
    match: { any: ['sour-bright', 'citrus', 'pomegranate'] },
  },
  'sweet-savory': {
    label: 'Карамель',
    emoji: '🍯',
    tagline: 'Мёд, соевый, бальзамик — sweet-savory',
    match: { any: ['sweet-savory', 'caramelized'] },
  },
  'herbal': {
    label: 'Травянистое',
    emoji: '🌿',
    tagline: 'Много свежих трав: базилик, кинза, эстрагон',
    match: { any: ['herbal', 'basil', 'cilantro', 'sage'] },
  },
  'umami': {
    label: 'Умами-бомба',
    emoji: '🧂',
    tagline: 'Глубокий вкус: соевый, мисо, устричный, гочуджан',
    match: { any: ['umami', 'soy'] },
  },
  'hearty': {
    label: 'Тёплое и сытное',
    emoji: '🥖',
    tagline: 'Густое, согревающее, для зимнего вечера',
    match: { any: ['hearty', 'warm', 'comforting'] },
  },
  'light': {
    label: 'Лёгкое и сложное',
    emoji: '🍵',
    tagline: 'Не пресное, но не тяжёлое',
    match: { any: ['light'] },
  },
};
