// Synonym map for search engine. Russian queries → recipe tags.
// Keys are lowercased query substrings (without word boundaries needed).
// Values are tags to match against recipe.cuisine / .protein / .textures / .sauceChar / .moods / .keyIngredients.

export const SYNONYMS = {
  // ===== textures =====
  'хрустящ': ['crunch', 'crispy-fried'],
  'хруст': ['crunch', 'crispy-fried'],
  'crisp': ['crunch', 'crispy-fried'],
  'свеж': ['fresh', 'crunch', 'light'],
  'прохлад': ['fresh', 'light'],
  'шёлков': ['silky', 'creamy'],
  'шелков': ['silky', 'creamy'],
  'сливочн': ['silky', 'creamy'],
  'крем': ['silky', 'creamy'],
  'кремов': ['silky', 'creamy'],
  'нежн': ['silky', 'creamy'],
  'сочн': ['juicy'],
  'мягк': ['silky'],
  'плотн': ['hearty'],
  'густ': ['hearty', 'silky'],
  'жирн': ['hearty'],
  'тает': ['silky', 'juicy'],
  'тающ': ['silky', 'juicy'],
  'липк': ['caramelized', 'sweet-savory'],
  'глянц': ['caramelized'],
  'обугл': ['grill', 'caramelized'],
  'тянущ': ['cheese', 'silky'],

  // ===== sauce character / taste =====
  'остр': ['spicy-hot'],
  'жгуч': ['spicy-hot'],
  'огнен': ['spicy-hot'],
  'spicy': ['spicy-hot'],
  'перчён': ['spicy-hot'],
  'перчен': ['spicy-hot'],
  'чили': ['spicy-hot'],
  'сладко-солён': ['sweet-savory'],
  'сладко-солен': ['sweet-savory'],
  'сладк': ['sweet-savory'],
  'карамел': ['sweet-savory', 'caramelized'],
  'медов': ['sweet-savory', 'honey'],
  'мёд': ['honey', 'sweet-savory'],
  'мед': ['honey', 'sweet-savory'],
  'кисл': ['sour-bright', 'citrus'],
  'лимон': ['citrus', 'lemon', 'sour-bright'],
  'цитрус': ['citrus', 'sour-bright'],
  'граната': ['pomegranate', 'sour-bright'],
  'гранат': ['pomegranate', 'sour-bright'],
  'кислинк': ['sour-bright'],
  'уксус': ['sour-bright'],
  'бальзамик': ['sour-bright', 'sweet-savory'],
  'умам': ['umami'],
  'соев': ['soy', 'umami'],
  'устричн': ['umami'],
  'хойсин': ['umami', 'sweet-savory'],
  'гочуджан': ['spicy-hot', 'umami'],
  'кочучан': ['spicy-hot', 'umami'],
  'мисо': ['umami', 'silky'],
  'солён': ['umami'],
  'солен': ['umami'],
  'трав': ['herbal'],
  'аромат': ['herbal'],
  'специ': ['spicy-hot', 'umami'],
  'пряное': ['spicy-hot', 'umami'],
  'пряност': ['umami', 'spicy-hot'],

  // ===== herbs / aromatics =====
  'базилик': ['basil', 'herbal'],
  'кинз': ['cilantro', 'herbal'],
  'кориандр': ['cilantro', 'herbal'],
  'мята': ['herbal'],
  'эстрагон': ['herbal'],
  'шалф': ['sage', 'herbal'],
  'розмарин': ['herbal'],
  'тимьян': ['herbal'],
  'петрушк': ['herbal'],
  'укроп': ['herbal'],
  'зелен': ['herbal', 'fresh'],
  'свеж зелен': ['herbal', 'fresh'],
  'имбир': ['ginger'],
  'чесн': ['garlic'],
  'кардамон': ['spice'],
  'кумин': ['spice'],
  'паприк': ['spice'],
  'куркум': ['curry', 'spice'],
  'заатар': ['middle-east', 'herbal'],
  'сумах': ['middle-east'],
  'харисс': ['spicy-hot', 'middle-east'],

  // ===== mood =====
  'быстр': ['quick'],
  'мин': ['quick'],
  '20 мин': ['quick'],
  '30 мин': ['quick'],
  'устал': ['quick', 'comforting'],
  'на скор': ['quick'],
  'наскор': ['quick'],
  'уютн': ['comforting', 'hearty', 'warm'],
  'согре': ['comforting', 'hearty', 'warm'],
  'тёпл': ['warm', 'hearty', 'comforting'],
  'тепл': ['warm', 'hearty', 'comforting'],
  'зимн': ['hearty', 'warm', 'comforting'],
  'праздн': ['fancy'],
  'гост': ['fancy'],
  'романт': ['fancy'],
  'свидан': ['fancy'],
  'день рожд': ['fancy'],
  'дома': ['comforting'],
  'лёгк': ['light'],
  'легк': ['light'],
  'для одного': ['quick'],
  'на одного': ['quick'],
  'для двоих': ['fancy'],
  'на двоих': ['fancy'],
  'на компани': ['fancy', 'hearty'],
  'для семь': ['comforting', 'hearty'],
  'сытн': ['hearty', 'warm'],
  'плотн': ['hearty'],
  'обильн': ['hearty'],
  'фаст': ['quick'],
  'утром': ['quick', 'light'],
  'обед': ['hearty', 'comforting'],
  'ужин': ['comforting', 'fancy'],
  'хочется чего-то': ['fancy'],
  'необычн': ['fancy'],
  'интересн': ['fancy', 'umami'],
  'эффектн': ['fancy', 'steak'],
  'настроени': ['fancy', 'comforting'],

  // ===== cooking method =====
  'жарен': ['pan-fry', 'sear', 'stir-fry'],
  'фри': ['crispy-fried', 'deep-fry'],
  'фритюр': ['crispy-fried', 'deep-fry'],
  'тушён': ['braise'],
  'тушен': ['braise'],
  'гриль': ['grill'],
  'на огне': ['grill'],
  'шашлык': ['grill', 'skewer'],
  'кебаб': ['grill', 'skewer', 'middle-east', 'turkey'],
  'шпажк': ['grill', 'skewer'],
  'тако': ['mexican', 'flatbread', 'latin'],
  'лаваш': ['flatbread'],
  'тортилья': ['flatbread', 'mexican'],
  'пита': ['flatbread', 'middle-east'],
  'wok': ['wok', 'stir-fry'],
  'вок': ['wok', 'stir-fry'],
  'рагу': ['braise', 'hearty', 'warm'],
  'запек': ['bake', 'hearty'],
  'духовк': ['bake', 'roast'],
  'сковород': ['pan-fry'],

  // ===== cuisines =====
  'итал': ['italy'],
  'италь': ['italy'],
  'пицц': ['italy', 'pizza'],
  'паст': ['italy', 'pasta'],
  'спагет': ['italy', 'pasta'],
  'кита': ['china'],
  'китай': ['china'],
  'азиат': ['china', 'japan', 'korea', 'thailand', 'vietnam', 'indonesia'],
  'азия': ['china', 'japan', 'korea', 'thailand', 'vietnam', 'indonesia'],
  'япон': ['japan'],
  'кор': ['korea'],
  'тай': ['thailand'],
  'таиланд': ['thailand'],
  'вьетнам': ['vietnam'],
  'индонез': ['indonesia'],
  'инд': ['india'],
  'индия': ['india'],
  'индийск': ['india'],
  'мексик': ['mexico', 'latin'],
  'латин': ['latin'],
  'перу': ['peru', 'latin'],
  'аргент': ['latin'],
  'бразил': ['latin'],
  'турец': ['turkey'],
  'турция': ['turkey'],
  'француз': ['france'],
  'францу': ['france'],
  'марок': ['morocco', 'middle-east'],
  'ливан': ['middle-east'],
  'израил': ['middle-east'],
  'греч': ['middle-east', 'greek'],
  'средиземн': ['middle-east'],
  'восточн': ['middle-east'],

  // ===== protein =====
  'мясо': ['beef', 'pork', 'chicken', 'turkey'],
  'мяса': ['beef', 'pork', 'chicken', 'turkey'],
  'мясн': ['beef', 'pork', 'chicken', 'turkey'],
  'говяд': ['beef'],
  'стейк': ['beef', 'steak'],
  'ребр': ['beef'],
  'фарш': ['beef', 'turkey', 'pork'],
  'свин': ['pork'],
  'грудинк': ['pork'],
  'вырезк': ['beef', 'pork'],
  'кур': ['chicken'],
  'крыл': ['chicken'],
  'крылышк': ['chicken'],
  'бедр': ['chicken'],
  'грудк': ['chicken'],
  'голен': ['chicken'],
  'индейк': ['turkey'],
  'панир': ['paneer', 'vegetarian', 'cheese'],
  'халлум': ['halloumi', 'vegetarian', 'cheese'],
  'фета': ['feta', 'vegetarian', 'cheese'],
  'моцарел': ['cheese'],
  'парм': ['parmesan', 'italy', 'cheese'],
  'буррат': ['burrata', 'italy', 'cheese'],
  'сыр ': ['cheese', 'paneer', 'halloumi'],
  'сыром': ['cheese'],
  'без мяса': ['vegetarian'],
  'вегет': ['vegetarian'],
  'постн': ['vegetarian'],
  'овощ': ['vegetarian', 'fresh'],

  // ===== ingredients / dishes / sides =====
  'томат': ['tomato'],
  'помидор': ['tomato'],
  'черри': ['tomato'],
  'рис ': ['rice'],
  'рисом': ['rice'],
  'лапш': ['noodles'],
  'нудл': ['noodles'],
  'удон': ['noodles', 'japan'],
  'рамен': ['noodles', 'japan'],
  'картош': ['potato'],
  'картофел': ['potato'],
  'пюре': ['potato'],
  'руккол': ['herbal', 'fresh', 'light'],
  'салат': ['fresh', 'light'],
  'огурец': ['fresh'],
  'авокадо': ['fresh'],
  'кокос': ['silky'],
  'манг': ['fresh'],
  'ананас': ['sweet-savory'],
  'яблок': ['sweet-savory'],
  'апельсин': ['citrus'],
  'батат': ['potato'],
  'цветн капуст': ['vegetarian'],
  'капуст': ['vegetarian'],
  'хлеб': ['flatbread'],

  // ===== specific dish keywords =====
  'болонез': ['bolognese', 'italy', 'pasta'],
  'болонья': ['bolognese', 'italy', 'pasta'],
  'белая болоньез': ['bolognese', 'italy'],
  'карри': ['curry'],
  'тикка': ['curry', 'india'],
  'масала': ['curry', 'india'],
  'буррит': ['mexican', 'latin'],
  'фахит': ['mexican', 'latin'],
  'булгог': ['korea', 'beef'],
  'кальб': ['korea', 'beef'],
  'катсу': ['japan', 'crispy-fried'],
  'терияк': ['japan', 'sweet-savory'],
  'тонкатсу': ['japan', 'crispy-fried'],
  'якитори': ['japan', 'chicken'],
  'гирос': ['middle-east', 'greek'],
  'шаверм': ['middle-east'],
  'шаурм': ['middle-east'],
  'сувлак': ['middle-east', 'greek'],
  'ризотто': ['italy', 'rice'],
  'гнокки': ['italy'],
  'лазань': ['italy', 'cheese'],
  'тажин': ['morocco', 'braise'],
  'таджин': ['morocco', 'braise'],
  'тахин': ['middle-east'],
  'тахини': ['middle-east'],
  'чимич': ['herbal', 'latin'],
  'песто': ['herbal', 'italy'],
  'трюфел': ['truffle', 'umami', 'fancy'],
  'кёфт': ['middle-east', 'beef'],
  'кофт': ['middle-east', 'beef'],
  'кебаб': ['middle-east', 'turkey'],
  'адана': ['turkey', 'beef'],
  'хойсин': ['china', 'sweet-savory'],
  'гунбао': ['china', 'spicy-hot'],
  'kung pao': ['china', 'spicy-hot'],
  'kung': ['china'],
  'pad krapao': ['thailand'],
  'пад-крап': ['thailand'],
  'крапао': ['thailand'],
  'larb': ['thailand'],
  'ларб': ['thailand'],
  'булд': ['korea', 'spicy-hot'],
  'токпок': ['korea'],
  'буль-дак': ['korea', 'spicy-hot'],
};


// Sensory chips → tag bundles. Used by feel-by-touch entries.
export const FEELINGS = {
  'crunch': {
    label: 'Хрустящее свежее',
    emoji: '🥬',
    tagline: 'Горячее блюдо с прохладным crunchy элементом',
    match: { any: ['crunch', 'fresh'] },
  },
  'silky': {
    label: 'Шёлковое сливочное',
    emoji: '🧈',
    tagline: 'Кремовые соусы, бархатный вкус',
    match: { any: ['silky', 'creamy'] },
  },
  'fire': {
    label: 'Огненное',
    emoji: '🔥',
    tagline: 'Жгучее, с чили, харисса, сычуань',
    match: { any: ['spicy-hot'], minSpice: 2 },
  },
  'juicy': {
    label: 'Сочное',
    emoji: '💧',
    tagline: 'Мясо, истекающее соком',
    match: { any: ['juicy'] },
  },
  'sour': {
    label: 'Кислое-яркое',
    emoji: '🍋',
    tagline: 'Цитрус, гранат, уксус — будит вкус',
    match: { any: ['sour-bright', 'citrus', 'pomegranate'] },
  },
  'sweet-savory': {
    label: 'Карамель',
    emoji: '🍯',
    tagline: 'Мёд, соевый, бальзамик — sweet-savory',
    match: { any: ['sweet-savory', 'caramelized'] },
  },
  'herbal': {
    label: 'Травянистое',
    emoji: '🌿',
    tagline: 'Много свежих трав: базилик, кинза, эстрагон',
    match: { any: ['herbal', 'basil', 'cilantro', 'sage'] },
  },
  'umami': {
    label: 'Умами-бомба',
    emoji: '🧂',
    tagline: 'Глубокий вкус: соевый, мисо, устричный, гочуджан',
    match: { any: ['umami', 'soy'] },
  },
  'hearty': {
    label: 'Тёплое и сытное',
    emoji: '🥖',
    tagline: 'Густое, согревающее, для зимнего вечера',
    match: { any: ['hearty', 'warm', 'comforting'] },
  },
  'light': {
    label: 'Лёгкое и сложное',
    emoji: '🍵',
    tagline: 'Не пресное, но не тяжёлое',
    match: { any: ['light'] },
  },
};
